// Package codegen generates typed contract clients from a decoded interface.
//
// The registry already holds everything a generator needs: types are
// recursive and fully resolved, and user-defined types are referenced by
// name. Generating from the stored ABI, rather than from the WASM, means a
// client can be produced for any registered contract — including a
// superseded version, by hash — without touching the network.
package codegen

import (
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/soroworks/sorovault/internal/model"
)

// Source identifies the contract a client is generated for. It is written
// into the file header and exported as constants, so a generated file says
// exactly which interface version it was built from.
type Source struct {
	ContractID string
	Network    string
	WasmHash   string
}

// sdkImport is the module the generated code builds on. Its contract.Client
// fetches the contract spec from the network and creates one method per
// function; the generated Client interface types those methods.
const sdkImport = "@stellar/stellar-sdk/contract"

// reservedTypeNames are identifiers the generated file declares or imports
// itself, plus TypeScript globals a contract type would shadow. A
// user-defined type with one of these names gets a trailing underscore.
var reservedTypeNames = map[string]bool{
	"sdk": true, "Buffer": true, "Client": true, "Errors": true, "connect": true,
	"contractId": true, "networkName": true, "wasmHash": true,
	"Array": true, "Map": true, "Set": true, "Promise": true, "Object": true,
	"String": true, "Number": true, "Boolean": true, "Symbol": true,
	"BigInt": true, "Error": true, "Date": true, "Function": true,
	"Record": true, "Partial": true, "Readonly": true,
}

var identifier = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

// TypeScript renders a client module for iface.
//
// The output imports @stellar/stellar-sdk (v14 or later) and the buffer
// package, declares every user-defined type, and exports a typed Client
// interface and a connect function returning a contract.Client narrowed to
// it. Type mappings follow the conventions of the Stellar CLI's own
// TypeScript bindings, so values round-trip through the SDK unchanged.
func TypeScript(iface *model.Interface, src Source) (string, error) {
	g := &tsGen{errorEnums: map[string]bool{}}
	for _, e := range iface.Types.ErrorEnums {
		g.errorEnums[e.Name] = true
	}

	w := &g.b
	fmt.Fprintf(w, "// Code generated by SoroVault from contract %s on %s. DO NOT EDIT.\n", src.ContractID, src.Network)
	fmt.Fprintf(w, "// Interface version (WASM hash): %s\n", src.WasmHash)
	if iface.Meta != nil {
		if v := iface.Meta["rssdkver"]; v != "" {
			fmt.Fprintf(w, "// Built with soroban-sdk %s\n", oneLine(v))
		}
	}
	w.WriteString("//\n// Requires @stellar/stellar-sdk >= 14 and buffer.\n\n")
	w.WriteString("import { Buffer } from \"buffer\";\n")
	fmt.Fprintf(w, "import * as sdk from %q;\n\n", sdkImport)

	fmt.Fprintf(w, "export const contractId = %q;\n", src.ContractID)
	fmt.Fprintf(w, "export const networkName = %q;\n", src.Network)
	fmt.Fprintf(w, "export const wasmHash = %q;\n", src.WasmHash)

	for _, s := range sortedBy(iface.Types.Structs, func(s model.Struct) string { return s.Name }) {
		g.writeStruct(s)
	}
	for _, u := range sortedBy(iface.Types.Unions, func(u model.Union) string { return u.Name }) {
		g.writeUnion(u)
	}
	for _, e := range sortedBy(iface.Types.Enums, func(e model.Enum) string { return e.Name }) {
		g.writeEnum(e)
	}
	g.writeErrors(iface.Types.ErrorEnums)
	g.writeClient(iface.Functions)

	if g.err != nil {
		return "", g.err
	}
	return g.b.String(), nil
}

type tsGen struct {
	b          strings.Builder
	errorEnums map[string]bool
	err        error
}

func (g *tsGen) writeDoc(indent, doc string) {
	doc = strings.TrimSpace(doc)
	if doc == "" {
		return
	}
	// A "*/" in a doc string would end the comment early.
	doc = strings.ReplaceAll(doc, "*/", "*\\/")
	g.b.WriteString(indent + "/**\n")
	for _, line := range strings.Split(doc, "\n") {
		g.b.WriteString(strings.TrimRight(indent+" * "+line, " ") + "\n")
	}
	g.b.WriteString(indent + " */\n")
}

func (g *tsGen) writeStruct(s model.Struct) {
	g.b.WriteString("\n")
	g.writeDoc("", s.Doc)
	name := typeName(s.Name)
	if s.IsTuple {
		parts := make([]string, len(s.Fields))
		for i, f := range s.Fields {
			parts[i] = g.tsType(f.Type)
		}
		fmt.Fprintf(&g.b, "export type %s = readonly [%s];\n", name, strings.Join(parts, ", "))
		return
	}
	fmt.Fprintf(&g.b, "export interface %s {\n", name)
	for _, f := range s.Fields {
		g.writeDoc("  ", f.Doc)
		fmt.Fprintf(&g.b, "  %s: %s;\n", propertyKey(f.Name), g.tsType(f.Type))
	}
	g.b.WriteString("}\n")
}

// writeUnion uses the SDK's tagged-object encoding: {tag, values}, where
// values is void for a unit case and a tuple of payloads otherwise.
func (g *tsGen) writeUnion(u model.Union) {
	g.b.WriteString("\n")
	g.writeDoc("", u.Doc)
	fmt.Fprintf(&g.b, "export type %s =", typeName(u.Name))
	if len(u.Cases) == 0 {
		g.b.WriteString(" never;\n")
		return
	}
	for _, c := range u.Cases {
		values := "void"
		if len(c.Values) > 0 {
			parts := make([]string, len(c.Values))
			for i, v := range c.Values {
				parts[i] = g.tsType(v)
			}
			values = "readonly [" + strings.Join(parts, ", ") + "]"
		}
		fmt.Fprintf(&g.b, "\n  | { tag: %q; values: %s }", c.Name, values)
	}
	g.b.WriteString(";\n")
}

func (g *tsGen) writeEnum(e model.Enum) {
	g.b.WriteString("\n")
	g.writeDoc("", e.Doc)
	fmt.Fprintf(&g.b, "export enum %s {\n", typeName(e.Name))
	for _, c := range e.Cases {
		g.writeDoc("  ", c.Doc)
		fmt.Fprintf(&g.b, "  %s = %d,\n", propertyKey(c.Name), c.Value)
	}
	g.b.WriteString("}\n")
}

// writeErrors emits one table of every contract error code, which is what
// the host reports and what contract.Client's Result errors carry. Codes
// from several error enums are merged; a code declared twice is an error,
// because the generated table could not say which meaning applies.
func (g *tsGen) writeErrors(enums []model.ErrorEnum) {
	type entry struct {
		code    uint32
		message string
	}
	byCode := map[uint32]entry{}
	for _, e := range enums {
		for _, c := range e.Cases {
			if prev, dup := byCode[c.Value]; dup && prev.message != c.Name {
				g.fail(fmt.Errorf("codegen: error code %d is both %s and %s", c.Value, prev.message, c.Name))
				return
			}
			byCode[c.Value] = entry{c.Value, c.Name}
		}
	}

	codes := make([]uint32, 0, len(byCode))
	for code := range byCode {
		codes = append(codes, code)
	}
	sort.Slice(codes, func(i, j int) bool { return codes[i] < codes[j] })

	g.b.WriteString("\n/** Contract error codes, as reported by the host. */\n")
	g.b.WriteString("export const Errors: Record<number, { message: string }> = {\n")
	for _, code := range codes {
		fmt.Fprintf(&g.b, "  %d: { message: %q },\n", code, byCode[code].message)
	}
	g.b.WriteString("};\n")
}

func (g *tsGen) writeClient(fns []model.Function) {
	g.b.WriteString("\n/** Typed methods of the contract. Each one simulates on call; sign and send the result to submit. */\n")
	g.b.WriteString("export interface Client {\n")
	for _, fn := range fns {
		if !identifier.MatchString(fn.Name) {
			g.fail(fmt.Errorf("codegen: function name %q is not a valid identifier", fn.Name))
			return
		}
		g.writeDoc("  ", fn.Doc)

		ret := "null"
		if len(fn.Outputs) > 0 {
			ret = g.tsType(fn.Outputs[0])
		}
		result := "Promise<sdk.AssembledTransaction<" + ret + ">>"

		if len(fn.Inputs) == 0 {
			fmt.Fprintf(&g.b, "  %s(options?: sdk.MethodOptions): %s;\n", fn.Name, result)
			continue
		}
		params := make([]string, len(fn.Inputs))
		for i, in := range fn.Inputs {
			params[i] = propertyKey(in.Name) + ": " + g.tsType(in.Type)
		}
		fmt.Fprintf(&g.b, "  %s(args: { %s }, options?: sdk.MethodOptions): %s;\n",
			fn.Name, strings.Join(params, "; "), result)
	}
	g.b.WriteString("}\n")

	g.b.WriteString(`
/**
 * Connect to the contract. The SDK reads its spec from the network and
 * builds the methods; this narrows them to the types above. contractId
 * defaults to the contract this file was generated from.
 */
export function connect(
  options: Omit<sdk.ClientOptions, "contractId"> & { contractId?: string },
): Promise<sdk.Client & Client> {
  return sdk.Client.from<Client>({ ...options, contractId: options.contractId ?? contractId });
}
`)
}

// tsType maps an interface type onto its TypeScript form.
func (g *tsGen) tsType(t model.Type) string {
	switch t.Kind {
	case model.KindVal:
		return "any"
	case model.KindBool:
		return "boolean"
	case model.KindVoid:
		return "void"
	case model.KindError:
		return "sdk.ErrorMessage"
	case model.KindU32, model.KindI32, model.KindU64, model.KindI64,
		model.KindU128, model.KindI128, model.KindU256, model.KindI256:
		return "sdk." + string(t.Kind)
	case model.KindTimepoint:
		return "sdk.Timepoint"
	case model.KindDuration:
		return "sdk.Duration"
	case model.KindBytes, model.KindBytesN:
		return "Buffer"
	case model.KindString, model.KindSymbol, model.KindAddress, model.KindMuxedAddress:
		return "string"
	case model.KindOption:
		return "sdk.Option<" + g.child(t.Inner) + ">"
	case model.KindVec:
		return "Array<" + g.child(t.Element) + ">"
	case model.KindMap:
		return "Map<" + g.child(t.Key) + ", " + g.child(t.Value) + ">"
	case model.KindResult:
		// The SDK's Result carries an ErrorMessage, not the contract's
		// error enum; the codes are in Errors.
		return "sdk.Result<" + g.child(t.Ok) + ">"
	case model.KindTuple:
		parts := make([]string, len(t.Elements))
		for i := range t.Elements {
			parts[i] = g.tsType(t.Elements[i])
		}
		return "readonly [" + strings.Join(parts, ", ") + "]"
	case model.KindUDT:
		if g.errorEnums[t.Name] {
			// An error enum used as a value is its numeric code.
			return "sdk.u32"
		}
		return typeName(t.Name)
	default:
		g.fail(fmt.Errorf("codegen: unsupported type kind %q", t.Kind))
		return "unknown"
	}
}

func (g *tsGen) child(t *model.Type) string {
	if t == nil {
		g.fail(fmt.Errorf("codegen: container type is missing its element type"))
		return "unknown"
	}
	return g.tsType(*t)
}

func (g *tsGen) fail(err error) {
	if g.err == nil {
		g.err = err
	}
}

// typeName is the TypeScript name for a user-defined type.
func typeName(name string) string {
	if reservedTypeNames[name] {
		return name + "_"
	}
	return name
}

// propertyKey quotes a key that is not a plain identifier.
func propertyKey(name string) string {
	if identifier.MatchString(name) {
		return name
	}
	return strconv.Quote(name)
}

// oneLine keeps a header value from breaking out of its comment.
func oneLine(s string) string {
	return strings.NewReplacer("\n", " ", "\r", " ").Replace(s)
}

// sortedBy returns a copy of items ordered by key, so output is stable
// regardless of the order the spec declared things in.
func sortedBy[T any](items []T, key func(T) string) []T {
	out := append([]T(nil), items...)
	sort.SliceStable(out, func(i, j int) bool { return key(out[i]) < key(out[j]) })
	return out
}
