// Code generated by SoroVault from contract CDZZXVGUCLBUTE3WDD6TF2NXPTBPOYTVPPBBIZMSPVIQLUG226XJ4PAN on testnet. DO NOT EDIT.
// Interface version (WASM hash): abc123
// Built with soroban-sdk 25.3.0#dcbea44513feb7734af6b6c4aced2c4a7a2715d0
//
// Requires @stellar/stellar-sdk >= 14 and buffer.

import { Buffer } from "buffer";
import * as sdk from "@stellar/stellar-sdk/contract";

export const contractId = "CDZZXVGUCLBUTE3WDD6TF2NXPTBPOYTVPPBBIZMSPVIQLUG226XJ4PAN";
export const networkName = "testnet";
export const wasmHash = "abc123";

export interface Proposal {
  description: string;
  vote_count: sdk.u64;
}

/**
 * Parameters defining a voting campaign.  Stored in contract storage and used as
 * inputs to the ZK circuit via public signals.  See `vote` method and circuit
 * comments for details on how these are used.
 *
 * `vote_scope` acts as a domain separator so the same ZK identity cannot
 * be reused across different voting campaigns.
 *
 * `citizenship_whitelist` stores encoded country codes (empty = unrestricted).
 * It is metadata only in the current circuit — enforcement would require a
 * dedicated circuit output signal.
 */
export interface VoteParams {
  birth_date_lowerbound: sdk.u64;
  citizenship_whitelist: Array<sdk.u64>;
  expiration_date_lower_bound: sdk.u64;
  identity_counter_upper_bound: sdk.u64;
  identity_ts_upper_bound: sdk.u64;
  vote_scope: sdk.u64;
  voting_question: string;
}

/** Contract error codes, as reported by the host. */
export const Errors: Record<number, { message: string }> = {
  1: { message: "AlreadyInitialized" },
  2: { message: "NotInitialized" },
  3: { message: "InvalidProposalIndex" },
  4: { message: "WrongNullifierSeed" },
  5: { message: "AlreadyVoted" },
  6: { message: "InvalidProof" },
  7: { message: "WrongPubSignalsLen" },
};

/** Typed methods of the contract. Each one simulates on call; sign and send the result to submit. */
export interface Client {
  /**
   * Cast a vote using a ZK Firma Digital Groth16 proof.
   *
   * The proof is verified by a cross-contract call to the `zk_verifier`
   * contract.  Double-voting is prevented via the nullifier stored in
   * persistent storage.
   *
   * ### Public signals layout (5 × 32-byte big-endian scalars)
   *
   *
   * | idx | meaning                                                       |
   * |-----|---------------------------------------------------------------|
   * | 0   | `pubkeyHash`     — Poseidon hash of the signing RSA pubkey    |
   * | 1   | `nullifier`      — unique per voter; prevents double-voting   |
   * | 2   | `ageAbove18`     — reveal flag (0 or 1); not checked here     |
   * | 3   | `nullifierSeed`  — must equal `vote_params.vote_scope`        |
   * | 4   | `signalHash`     — binding commitment (see identity_gate)     |
   *
   * * `voter`          – account casting the vote (must authorise the tx)
   * * `proposal_index` – 0-based index into the proposals list
   * * `pub_signals`    – 5 public circuit outputs (see table above)
   * * `a`              – Groth16 proof poi
   */
  vote(args: { voter: string; proposal_index: sdk.u32; pub_signals: Array<Buffer>; a: Buffer; b: Buffer; c: Buffer }, options?: sdk.MethodOptions): Promise<sdk.AssembledTransaction<sdk.Result<void>>>;
  has_voted(args: { nullifier: Buffer }, options?: sdk.MethodOptions): Promise<sdk.AssembledTransaction<boolean>>;
  /**
   * One-time initialization.  Must be called before any votes can be cast.
   *
   * * `admin`                 – address that deployed this contract
   * * `verifier_id`           – address of the deployed `zk_verifier` contract
   * * `vote_params`           – campaign configuration
   * * `proposal_descriptions` – human-readable label for each option
   */
  initialize(args: { admin: string; verifier_id: string; vote_params: VoteParams; proposal_descriptions: Array<string> }, options?: sdk.MethodOptions): Promise<sdk.AssembledTransaction<sdk.Result<void>>>;
  get_proposal(args: { index: sdk.u32 }, options?: sdk.MethodOptions): Promise<sdk.AssembledTransaction<sdk.Result<Proposal>>>;
  get_total_votes(options?: sdk.MethodOptions): Promise<sdk.AssembledTransaction<sdk.u64>>;
  get_vote_params(options?: sdk.MethodOptions): Promise<sdk.AssembledTransaction<sdk.Result<VoteParams>>>;
  get_proposal_count(options?: sdk.MethodOptions): Promise<sdk.AssembledTransaction<sdk.u32>>;
}

/**
 * Connect to the contract. The SDK reads its spec from the network and
 * builds the methods; this narrows them to the types above. contractId
 * defaults to the contract this file was generated from.
 */
export function connect(
  options: Omit<sdk.ClientOptions, "contractId"> & { contractId?: string },
): Promise<sdk.Client & Client> {
  return sdk.Client.from<Client>({ ...options, contractId: options.contractId ?? contractId });
}
